import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/shared/AppLayout";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({ subsets: ["latin"], weight: ["100", "400", "700", "900"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >

        <AppLayout page={children}/>
        <Toaster richColors  position="top-center"  theme="light"/>
      </body>
    </html>
  );
}
